# Generated by Django 6.0.1 on 2026-01-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="isbn_number",
            new_name="isbn",
        ),
    ]
